CC = clang++
FLAGS =  -W -Wall  -g -std=c++11

all:  test-0 test-1 test-2 test-3 test-4 

test-0: test/test-0.cpp
	$(CC) $^ $(FLAGS) -o $@

test-1: test/test-1.cpp
	$(CC) $^ $(FLAGS) -o $@

test-2: test/test-2.cpp
	$(CC) $^ $(FLAGS) -o $@

test-3: test/test-3.cpp
	$(CC) $^ $(FLAGS) -o $@

test-4: test/test-4.cpp
	$(CC) $^ $(FLAGS) -o $@ 


